name: Run Cypress tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Cypress tests
          run: |
            cd api
            npm install
            npm run dev &
            cd ..
            cd client
            npm install
            npm run dev &
            npx wait-on http://localhost:5173 npx cypress run
          env:
            NODE_ENV: development
