name: Run Cypress tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          
          mysql -e "CREATE DATABASE IF NOT EXISTS rallysphere;"
          mysql -u root -e "source /home/runner/work/RallySphere-TestyE2E/RallySphere-TestyE2E/database/rallysphere.sql" 

      - name: Install and start API
        run: |
          cd api
          npm install
          npm run dev & 
          cd ..

      - name: Install and start client
        run: |
          cd client
          npm install
          npm run dev & 
          cd ..

      - name: Wait for both servers to be ready
        run: |
          npx wait-on http://localhost:5173 
          npx wait-on http://localhost:3000  

      - name: Run Cypress tests
        run: |
            cd client
            npx cypress run

    env:
        NODE_ENV: development
